import numpy as np
import matplotlib.pyplot as plt
import pandas as pd                     
plt.style.context(['science','ieee'])
ddpg_reward = pd.read_csv("./temp_data/20_ddpg_reward.csv")
pn_reward = pd.read_csv("./temp_data/20_pn_reward.csv")
plt.figure(figsize=(15,10))
with plt.style.context(['science','ieee']):
    # ax1 = plt.subplots(1,3,1)
    fig, ax = plt.subplots()
    ax.plot(ddpg_reward['Value'])
    ax.plot(pn_reward['Value'])
    ax.grid()
    ax.set(xlabel="number of policy iterations")
    ax.set(ylabel="Cell average spetrum efficiency[bps/Hz]")
    ax.legend(['Wolpertinger', 'Pointer Network'])
    fig.savefig('./20_user_reward.png', dpi=600)
    
    
# with plt.style.context(['science','ieee']):
#     # ax1 = plt.subplots(1,3,1)
#     plt.plot(range(1,1001),reward_15_user_value)
# #     plt.grid()
#     plt.xlabel('number of policy iterations')
#     plt.ylabel('Cell average spetrum efficiency[bps/Hz]')
#     plt.autoscale(tight=True)
#     plt.savefig("15_user_reward.png")
#     plt.close()

# greedy_10_user = np.load("./Greedy_10_user_capacity_10_10_0.npy")
# greedy_15_user = np.load("./Greedy_15_user_capacity_10_10_0.npy")
# RL_10_user = np.load("./RL_10_user_capacity_10_10_0.npy")
# RL_15_user = np.load("./RL_15_user_capacity_10_10_0.npy")
# fig, ax = plt.subplots()
# ax.plot(range(1,1101), greedy_10_user)
# ax.plot(range(1,1101), RL_10_user)
# # plt.plot(range(1,len(capacity)+1),greedy_capacity,label="greedy alg",color='red')
# # plt.legend()
# ax.grid()
# ax.set(xlabel="Transmit Time Interval")
# ax.set(ylabel="Cell spetrum efficiency (bps/Hz)")
# ax.legend(['Greedy method', 'Proposed method'])
# fig.savefig('./10_user_capacity.png', dpi=600)

# fig, ax = plt.subplots()
# ax.plot(range(1,1101), greedy_15_user)
# ax.plot(range(1,1101), RL_15_user)
# # plt.plot(range(1,len(capacity)+1),greedy_capacity,label="greedy alg",color='red')
# # plt.legend()
# ax.grid()
# ax.set(xlabel="Transmit Time Interval")
# ax.set(ylabel="Cell spetrum efficiency (bps/Hz)")
# ax.legend(['Greedy method', 'Proposed method'])
# fig.savefig('./15_user_capacity.png', dpi=600)